const eventsdata = [
  {
    organizer: "1",
    name: "Mic Drop",
    description: "This is annual event of our council",
    price: 45.03,
    dateofevent: "22-09-2022",
    location: "Fr.Agnel,Bandra",
    type: "Music Festival",
  },
  {
    organizer: "1",
    name: "Hackathon",
    description: "This is annual Hackathon of our Council",
    price: 45.03,
    dateofevent: "22-09-2022",
    location: "Fr.Agnel,Bandra",
    type: "Music Festival",
  },
  {
    organizer: "1",
    name: "Sunburn Festival",
    description: "This is annual event of our council",
    price: 45.03,
    dateofevent: "22-09-2022",
    location: "Fr.Agnel,Bandra",
    type: "Music Festival",
  },
  {
    organizer: "1",
    name: "Sunburn Festival",
    description: "This is annual event of our council",
    price: 45.03,
    dateofevent: "22-09-2022",
    location: "Fr.Agnel,Bandra",
    type: "Music Festival",
  },
  {
    organizer: "1",
    name: "Sunburn Festival",
    description: "This is annual event of our council",
    price: 45.03,
    dateofevent: "22-09-2022",
    location: "Fr.Agnel,Bandra",
    type: "Music Festival",
  },
  {
    organizer: "1",
    name: "Sunburn Festival",
    description: "This is annual event of our council",
    price: 45.03,
    dateofevent: "22-09-2022",
    location: "Fr.Agnel,Bandra",
    type: "Music Festival",
  },
];

export default eventsdata;
